JDP-240501-21 - ProductController - rzeczywista implementacja
piotr-grosicki/project-jdp-2405-01 pull request #37
Opened 2024-05-20 21:35 UTC by Knutek1

- W rekordach CreateProductRequest i UpdateProductRequest dodałem pola: price, quantity i group.
- Usunąłem DeleteProductRequest
- W ProductResponse zrobiłem @JsonIgnoreProperties dla pola productList z Group group
  W GroupResponse zrobiłem @JsonIgnoreProperties dla pola group z List<Product> products. Bez tego zapisu Product i Group wzajemnie się zapętlały i przy żądaniu GET odpowiedź w Postmanie miała ponad 5000 linijek :).
- Utworzyłem 2 typy wyjątków (ogólny by w niektórych przypadkach nie przyjmowało null i błędny id produktu)
- Utworzyłem GlobalHandlingException by dawało jakąś odpowiedź w JSON.
- CartController (wstępna implementacja) uzupełniłem o przykładową wartość dla pola typu Group. 
- Zrobiłem rzeczywistą implementację ProductController
- Utworzyłem ProductMapper
- Utworzyłem ProductService

2024-05-21 18:05 UTC, Sebczak requested changes
Wyjatki spoko, liczylem ze ktos to napisze takze to na plus ale trzeba poprawic metody do aktualizacji produktu i usuwanie produktu.

2024-05-21 18:05 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
Co w przypadku pustych pol? Czy jesli mam produkt lodowka i wrzuce request "" to nazwa lodowka zostanie zamieniona na pusta? chyba tak. Dodatkowo widze ze dodales warunek na null tylko dla nazwy, co sie stanie jesli ustawie cene na null? chyba zostanie ustawiona cena null. Z tego co widze to tylko name i id sa nullable = false takze warto cos takiego sprawdzic. Dodatkowo przy kazdym uzyciu updateProduct jest zapis do bazy co moze ja bardzo obciazyc. Warto zastanowic sie nad jakims sposobem sprawdzania czy dane parametry zostaly zmienione i jesli tak to wtedy i tylko wtedy baza powinna zapisywac obiekt. Pozoli to bazie "odpoczac" od ciaglego updateowania rekorkow.

2024-05-21 18:05 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        }
To mozna one linerem napisac. O takim         
`Product product = productRepository.findById(id).orElseThrow(() -> new ProductNotFoundException(String.format("Product with id: %d could not be found", id)));`

2024-05-21 19:55 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
No ale co w przypadku gdy w tą lodówkę wrzucisz request "." albo "?". Przecież to nie jest lepsza sytuacja. Ja bym w tym przypadku się raczej zdecydował na podejście zerojedynkowe (null , nienull) bo nie możemy traktować wpisującego produkt jak głupka, który nie wie co wpisuje. Raczej jak już wpisuje to coś konkretnego, a bardziej prawdopodobna sytuacja jest wtedy gdy zapomni o elemencie (np. name), ale wtedy broni to obsługa null. Jak zaczniemy wchodzić za bardzo w ciągi znaków to bedziesz musiał powykluczać wszystkie bezsensowne nazwy dla produktu. Sprawdzanie null dla name ustawiłem bo wychodziłem z założenia, że w produkcie najważniejsze jest id i nazwa, ale mogę poustawiać dla pozostałych elementów - nie jest to dużo roboty. Equalsy również

2024-05-21 19:58 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        }
Można, ale taki zapis też jest dopuszczalny i czytelny. Klasa nie jest aż taka długa, żeby konieczne było walczenie o każdą linijkę.

2024-05-21 20:08 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
No nie wiem dla mnie walidacja backendowa jest dosc wazna tak aby serwis odpowiednio dobrze reagowal na dane wejsciowe. Nie mozemy zakladac ze user jest na tyle inteligentny i nie ustawic ceny np na 0 albo co gorsza ujemnej ceny i tak samo z iloscia przedmiotow.

2024-05-21 20:09 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        }
Ok

2024-05-21 20:18 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
OK, ale w takim razie jak zabezpieczysz dane przed wpisywaniem "." , "-", "$" - wg mnie bez sensu w to brnąć., można poustawiać nulle dla wszystkich, dla ceny i ilości wartości dodatnie bo to łatwe, ale jak chcesz zablokować wszsytkie głupoty które można zrobić na ciągach znaków?

2024-05-21 20:21 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
Dobra, nazwa name i description moze zostac tak jak jest, ale dalbym walidaje ceny i ilosci produktow.

2024-05-21 20:56 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        product.setGroup(updateProductRequest.group());
już to właśnie robię ;)

2024-05-21 21:11 UTC, Knutek1 commented
W poprawkach : 
-utworzyłem NegativeValueException dla sprawdzania czy nie chcemy wpisac ujemnej ilości lub ceny.
-dodałem sprawdzenie dla wszystkich wartości (oprócz Group) czy nie są null przy tworzeniu i update'owaniu Produktu

2024-05-21 21:21 UTC, Sebczak requested changes

2024-05-21 21:21 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Product with given Id doesn't exist", HttpStatus.BAD_REQUEST);
tutaj mozna wyciagnac message z productNotFoundException.getMessage, zamiast pisac tekst

2024-05-21 21:21 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        groupRepository.findById(createProductRequest.group().getId()).orElseThrow(() -> new GroupNotFoundException(String.format("Group with id: %d could not be found", createProductRequest.group().
message z wyjatku mozna wrzucic do wyjatku samego w sobie, zobacz PR Grzeska.

2024-05-21 21:21 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
Ok tutaj jakas walidacja jest ale masz OR(||) i jak tak zrobisz to wystarczy zeby tylko 1 wartosc byla ok i dalej przejdzie trzaba dac AND(&&)

2024-05-21 21:21 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
Tak samo tutaj musi byc AND binarny

2024-05-21 21:25 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
Wystarczy jedna wartość ujemna żeby rzucić wyjątek. Gdzie tu jest błąd bo nie widzę?

2024-05-21 21:26 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
to samo co wyżej

2024-05-22 17:29 UTC, Sebczak approved these changes
Nie jestem pewien czy JsonIgnoreProperties jest najlepszym wyjsciem ale jesli dziala to ok

2024-05-22 17:29 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
Tak masz racje, moja wina sorki

2024-05-22 17:29 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +            throw new NegativeValuesException();
racja

2024-05-22 17:29 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Negative value is not allowed",HttpStatus.BAD_REQUEST);
To tez mozna wyciagnac z wyjatku ale to juz w nowym pr najwyzej

2024-05-22 17:29 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Null value is not allowed",HttpStatus.BAD_REQUEST);
To tez mozna wyciagnac z wyjatku ale to juz w nowym pr najwyzej

2024-05-22 17:48 UTC, merged