JDP240501-23-CartController-implementacja
piotr-grosicki/project-jdp-2405-01 pull request #38
Opened 2024-05-21 19:04 UTC by KayakOnWheels

- dodałem metody deleteProductFromCart i createOrderFromCart w CartService
- dodałem rzeczywistą implementację metod w CartController
- w CartController zmieniłem adres endpointu createOrderFromCart przyjmujący zmienną na /order i wymagający podania request body, zamiast zmiennej w adresie
- dodałem pole shippingAddress w CreateOrderRequest
- usunąłem pole price z AddProductToCartRequest
- w OrderResponse zmieniłem status na boolean
- dodałem OrderMapper skopiowany z brancha implementującego order na potrzeby CartService

2024-05-21 19:19 UTC, Sebczak requested changes
Fajny sposob z wyjatkami, zamiast caly czas pisac wiadomosc to jest 1 wiadomosc i ty tylko wysylasz id a wyjatek zwraca nam co jest nie tak ale wg metodka ktora tworzy order zle dziala i ja bym ja poprawil.

2024-05-21 19:19 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/dto/request/CreateOrderRequest.java
> +public record CreateOrderRequest (Long cartId, Long userId, BigDecimal totalPrice, String shippingAddress, boolean status ){
Czy potrzebujemy ceny adresu i statusu w tym requescie? status mozemy ustawic na false, cene mozemy wyciagnac z koszyka a aders z usera

2024-05-21 19:19 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        );
Czy ja dobrze mysle:
przedmioty z koszyka kosztuja lacznie powiedzmy 500$ 
ja wysylam 5$ i status na true. I wtedy automatyczny order serwis widzi ze od razu zaplacilem i oni shippuja mi itemy z koszyka. Jesli tak to chyba tak nie powinno to dzialac.

2024-05-21 19:58 UTC, KayakOnWheels commented on src/main/java/com/kodilla/ecommercee/dto/request/CreateOrderRequest.java
> +public record CreateOrderRequest (Long cartId, Long userId, BigDecimal totalPrice, String shippingAddress, boolean status ){
hm, faktycznie, czyli w zasadzie można wrócić do przekazania jedynie cartId w adresie i wywalić response body

2024-05-21 20:22 UTC, KayakOnWheels commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        );
to jest user friendly - w końcu kto by nie chciał sam sobie ustalać ceny zakupów :D, poprawione w kolejnych commitach

2024-05-21 20:31 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/dto/request/CreateOrderRequest.java
> +public record CreateOrderRequest (Long cartId, Long userId, BigDecimal totalPrice, String shippingAddress, boolean status ){
A jak dodasz order do usera? no chyba ze usera wyciagniesz z cart to wtedy z requestu mozna i userId wyrzucic

2024-05-21 20:34 UTC, Sebczak approved these changes

2024-05-21 20:43 UTC, Sebczak approved these changes

2024-05-22 18:42 UTC, pavgos22 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
Tu w OrderResponse nie ma być false? Chyba false oznacza nieopłacone zamówienie, a true opłacone.

2024-05-22 22:05 UTC, KayakOnWheels commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
To raczej bez znaczenia, to był tylko sztuczny response dla testów. Powinna być zmieniona przy faktycznej implementacji

2024-05-23 17:10 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/entity/CartItem.java
> +@Getter
Jak dajesz Data to juz masz Getter annotacje

2024-05-23 17:11 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/entity/CartItem.java
> +@Table(name = "CART_ITEM")
Trzymajmy sie konwencji projektu takze CART_ITEMS

2024-05-23 19:24 UTC, merged