JDP-240501 Dodanie do programu Swaggera, Dopisanie validacji.
piotr-grosicki/project-jdp-2405-01 pull request #44
Opened 2024-05-28 14:32 UTC by Knutek1

1) Dodałem Swaggera do programu dla przeglądania dokumentacji endpointów pod adresem: 
http://localhost:8080/swagger-ui/index.html
2) Dodałem w requestach adnotacje @NotNull i @Valid przy wszelkich ID- daje to małą informację o tym, że request jest błędny : "Invalid request content. (myślę że to lepsze rozwiązanie niż wewnętrzny błąd serwera).
3) W ProductService dodałem metodę sprawdzającą czy wartości są null lub ujemne, żeby się kod w innych metodach nie dublował.

2024-05-29 13:46 UTC, Sebczak requested changes
Jeśli chcemy w taki sposób obsługiwać Null wyjątki to fajnie byłoby zrobic research jaki to jest wyjątek i potem go dodać do wyjątków o dać mu jakiś Message.

2024-05-29 13:46 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/dto/request/CreateProductRequest.java
> +public record CreateProductRequest(String name, String description, BigDecimal price, Integer quantity, @Valid @NotNull Long groupId) {
A sprawdziłeś czy tutaj name, description, Price, quantity może być nullem?

2024-05-29 13:46 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/dto/request/LockUserRequest.java
> +public record LockUserRequest(@Valid @NotNull Long userId, String username, String password) {
To samo co wyżej

2024-05-29 13:46 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/dto/request/UpdateGroupRequest.java
> +public record UpdateGroupRequest(@Valid @NotNull Long id, String name) {
To samo co wyżej

2024-05-29 13:46 UTC, Sebczak commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +    private void nullOrNegativeValueCheck(String name, String description, BigDecimal price, Integer quantity) throws NullValueException, NegativeValuesException {
Jeśli robimy walidaje NotNull to nie potrzebujemy tutaj sprawdzać tego wystarczy negative value check

2024-05-29 17:19 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/dto/request/CreateProductRequest.java
> +public record CreateProductRequest(String name, String description, BigDecimal price, Integer quantity, @Valid @NotNull Long groupId) {
Tak sprawdzałem, przeprowadziliśmy przecież razem na ten temat długą dyskusję na moim PR z ProductController. Podobnie jak i Ty robiłeś to w swoim kodzie - w Servisach te elementy są sprawdzane przez porównanie do nulla. Tu nie chodziło i wyważanie drzwi nie wiadomo jakie uszczelnianie programu. Chodziło o wyrzucenie błędu 500 przy wszystkich metodach findById() w Servisach bo daje zamazane info o błędzie serwera, kiedy to request zawiera błędy. Po dodaniu @NotNulli do wszystkich ID ten problem znika i przynajmniej użytkownik ma info że request jest inwalidą ;).

2024-05-29 17:23 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/dto/request/LockUserRequest.java
> +public record LockUserRequest(@Valid @NotNull Long userId, String username, String password) {
Przecież sam to robisz metodą isNullOrEmpty w UserService i wyrzucasz NullValueException() :)

2024-05-29 17:38 UTC, Knutek1 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +    private void nullOrNegativeValueCheck(String name, String description, BigDecimal price, Integer quantity) throws NullValueException, NegativeValuesException {
Ale u Ciebie w UserService jest bliźniacza funkcja - nie wyrzucałem jej. Chodziło o to, żeby wyeliminować błędy 500, bo zamazują obraz na informację o wadliwym requeście - lepsze rozwiązanie dla użytkownika, bo wie że błąd leży po jego stronie.

2024-05-29 19:43 UTC, Sebczak commented
Mi chodzi o to aby właśnie usunąć NullValueException i zastąpić to annotacjami NotNull i Valid po czym dodać wyjątek, który rzuca null value i go obsłużyć.

2024-05-30 05:55 UTC, Knutek1 commented
Ok to skoro się projekt grupowy skończył to może każdy przerobić sobie finalną wersję programu według własnego pomysłu. Odłączam PR żeby już nie wisiał.

2024-05-30 05:55 UTC, closed without merging